# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
# SPDX-License-Identifier: CC0-1.0
#
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for NodeJS packages
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # prevents normal PRs, allows security PRs
    assignees:
      - unru-jo

  # Maintain dependencies for Docker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # prevents normal PRs, allows security PRs
    assignees:
      - unru-jo

  # Maintain dependencies for GitHub actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # prevents normal PRs, allows security PRs
    assignees:
      - unru-jo
