# SPDX-FileCopyrightText: 2024 Johannes Unruh <johannes.unruh@dlr.de>
# SPDX-FileCopyrightText: 2024 Florian Heinrich <florian.heinrich@dlr.de>
#
# SPDX-License-Identifier: Apache-2.0

site_name: Federated Learning Demonstrator Frontend

repo_name: fl-frontend
repo_url: https://github.com/DLR-KI/fl-demonstrator-frontend

nav:
  - Home: index.md
#  - API: "api/index.html"

theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - toc.follow
    - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: blue

plugins:
  - search

extra:
  social:
    - icon: dlr-logo
      link: https://www.dlr.de/en
    - icon: dlr-ki
      link: https://www.dlr.de/ki/en
    - icon: fontawesome/brands/square-gitlab
      link: https://github.com/DLR-KI/fl-demonstrator

#extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
#  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
#  - javascripts/katex.js

extra_css:
  #- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - styles/style.css

copyright: |
  &copy; 2024
  <a href="https://www.dlr.de/en/ki/about-us/departments/algorithms-hybrid-solutions" target="_blank" rel="noopener">
    DLR KI ALG
  </a>

