# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
# SPDX-License-Identifier: Apache-2.0

site_name: Federated Learning Demonstrator Frontend

repo_name: fl-frontend
repo_url: https://github.com/DLR-KI/fl-demonstrator-frontend
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - toc.follow
    - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: blue

plugins:
  - search

extra:
  social:
    - icon: dlr-logo
      link: https://www.dlr.de/en
    - icon: dlr-ki
      link: https://www.dlr.de/en/ki
    - icon: fontawesome/brands/square-github
      link: https://github.com/DLR-KI

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.44/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.44/dist/contrib/auto-render.min.js
  - javascripts/katex.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.44/dist/katex.min.css
  - styles/style.css

copyright: |
  &copy; 2026
  <a href="https://www.dlr.de/en/ki/about-us/departments/algorithms-hybrid-solutions" target="_blank" rel="noopener">
    DLR KI ALG
  </a>
